on: [push]
jobs:
  no_ampersands:
    runs-on: ubuntu-latest
    steps:
      - run: |
          false
          echo bad
  ampersands:
    runs-on: ubuntu-latest
    steps:
      - run: >
          false &&
          echo bad
